<h1><?php echo $this->_variables['title']; ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper('UsersMenuHelper')->show(); ?>
</div>

<div>
    <table class="table table-hover">
        <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Password</th>
            <th colspan="2"></th>
        </tr>
    <?php foreach ($this->_variables['users'] as $user): ?>
        <tr>
            <td><?php echo $user->getId(); ?></td>
            <td><?php echo $user->getEmail(); ?></td>
            <td><?php echo $user->getPassword(); ?></td>
            <td><a href="/users/update/id/<?php echo $user->getId(); ?>/">update</a></td>
            <td><a href="/users/remove/id/<?php echo $user->getId(); ?>/">remove</a></td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>