<h1><?php $this->out($this->title); ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper('UsersMenuHelper')->show(); ?>
</div>

<div>
    <table class="table table-hover">
        <tr>
            <th>Id</th>
            <th>Email</th>
            <th>Password</th>
            <th colspan="2"></th>
        </tr>
    <?php foreach ($this->users as $user): ?>
        <tr>
            <td><?php $this->out($user->getId()); ?></td>
            <td><?php $this->out($user->getEmail()); ?></td>
            <td><?php $this->out($user->getPassword()); ?></td>
            <td><a href="/users/update/id/<?php $this->out($user->getId()); ?>/">update</a></td>
            <td><a href="/users/remove/id/<?php $this->out($user->getId()); ?>/">remove</a></td>
        </tr>
    <?php endforeach; ?>
    </table>
</div>