<h1><?php echo $this->_variables['title']; ?></h1>

<div>
    <?php echo $this->_viewHelperBroker->getHelper('UsersMenuHelper')->show(); ?>
</div>

<div>
    <?php echo $this->_viewHelperBroker->getHelper(
        'FormHelper',
        array('action'      => '/users/updateDo/',
              'id'          => 'fr1',
              'method'      => 'post',
              'buttonValue' => 'Update',
              'controls'    => array(
                  array(
                      'field'       => 'id',
                      'type'        => 'number',
                      'value'       => $this->_variables['user']->getId(),
                      'disabled'    => 'disabled'
                  ),
                  array(
                      'field'       => 'id',
                      'type'        => 'hidden',
                      'value'       => $this->_variables['user']->getId(),
                  ),
                  array(
                      'field'       => 'email',
                      'type'        => 'email',
                      'value'       => $this->_variables['user']->getEmail()
                  ),
                  array(
                      'field'       => 'password',
                      'type'        => 'text',
                      'value'       => $this->_variables['user']->getPassword()
                  )
              )
        ))->show(); ?>
</div>